# Generated by Django 4.2 on 2023-06-30 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('client_dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('part_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='app_tienda/products')),
                ('price_usd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tienda.order')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tienda.product')),
            ],
        ),
    ]
