# Generated by Django 4.2 on 2023-06-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
