# Generated by Django 4.2 on 2023-06-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('App_Tienda_de_repuestos', '0005_remove_order_product_id_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_dni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.client'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
