# Generated by Django 4.2 on 2023-06-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda_de_repuestos', '0007_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
