# Generated by Django 4.2 on 2023-06-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Tienda_de_repuestos', '0008_alter_product_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.FloatField(),
        ),
    ]
