# Generated by Django 4.2 on 2023-06-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default=0, upload_to='Users/avatars'),
            preserve_default=False,
        ),
    ]
