# Generated by Django 4.2 on 2023-06-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_client_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
